# Generated by Django 4.1.3 on 2022-11-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imobiliariaSA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoImovel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Escolha uma foto",
                        null=True,
                        upload_to="media/fotos/%Y/%m/%d",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Descrição", verbose_name="Descrição"),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imobiliariaSA.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fotos dos imoveis",
                "db_table": "tab_fotoImovel",
                "managed": True,
            },
        ),
    ]
